//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appswindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplyees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emplyees()
        {
            this.achats = new HashSet<achats>();
            this.ventes = new HashSet<ventes>();
        }
    
        public int id_emp { get; set; }
        public byte[] image_emp { get; set; }
        public string login_emp { get; set; }
        public string password_emp { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<int> Ntele { get; set; }
        public string type_emp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<achats> achats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventes> ventes { get; set; }
    }
}
