//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appswindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produits()
        {
            this.achats = new HashSet<achats>();
            this.ventes = new HashSet<ventes>();
        }
    
        public int id_produit { get; set; }
        public string nom_produit { get; set; }
        public decimal prix_unitare_prod { get; set; }
        public string type_produit { get; set; }
        public decimal prix_vent { get; set; }
        public string code_bare { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<achats> achats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventes> ventes { get; set; }
    }
}
