//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appswindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventes
    {
        public int id_vente { get; set; }
        public System.DateTime date_vente { get; set; }
        public int qentity_vente { get; set; }
        public decimal prix_unitare_achat { get; set; }
        public decimal prix_vente { get; set; }
        public string mouvement { get; set; }
        public int id_produit { get; set; }
        public int id_client { get; set; }
        public int id_emp { get; set; }
        public string nom_prod { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual emplyees emplyees { get; set; }
        public virtual produits produits { get; set; }
    }
}
